//
//  LoginViewController.swift
//  TaekwondoPoints
//
//  Created by cassio on 11/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


// MARK: - LoginViewController
final class LoginViewController: UIViewController, LoginViewable {
    
    

    var interactor: LoginInteractorProtocol = LoginInteractor()
    var router: LoginRouterProtocol = LoginRouter()
    
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
     
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        
    }




    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        loadCredentials()

    }
    
    
    private func loadCredentials() {
        let request = Login.LoadCredentials.Request()
        interactor.loadCredentials(request: request)
    }
    
    //MARK: - receive events from UI
    
    @IBOutlet private weak var nomeusuarioTextField: UITextField!
    @IBOutlet weak var senhaTextField: UITextField!
    @IBOutlet weak var senhaSwitch: UISwitch!
    

    
    
    // MARK: - IBActions
    
    @IBAction func login(_ sender: Any) {
        
        //mostrarLoadingView()
        let request = Login.Autenticacao.Solicitar(usuarionome: nomeusuarioTextField.text,
                                                  senha: senhaTextField.text,
                                                  amarzenarLogin: senhaSwitch.isOn)
        interactor.login(request: request)
        
    }
    
    
    @IBAction func cadastro(_ sender: Any) {
        
        let request = Login.Autenticacao.Solicitar(usuarionome: nomeusuarioTextField.text,
                                                 senha: senhaTextField.text,
                                                 amarzenarLogin: senhaSwitch.isOn)
        interactor.register(request: request)
    }
    
}

