//
//  LoginModels.swift
//  TaekwondoPoints
//
//  Created by cassio on 11/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
    // MARK: Use cases

    enum Something
    {
        struct Request{}

        struct Response
        {
            let lembrarNomeusuario: Bool
            let nomeusuario: String?
        }

        struct ViewModel
        {
            let lembrarMeIsOn: Bool
            let nomeusuarioText: String?
        }
    }
    
    enum Autenticacao{
        
        struct Solicitar {
            let usuarionome: String?
            let senha: String?
            let amarzenarLogin: Bool
        }
        
        struct Resposta {
            let error: LoginError?
        }
        
    }
    
    enum LoginError: Error {
        case missingCredentials
        case loginFailed(String)
        case registerFailed(String)
    }
    
//    enum SomethingElse
//    {
//        struct Request
//        {
//
//        }
//
//        struct Response
//        {
//
//        }
//
//        struct ViewModel
//        {
//
//        }
//    }
}
