//
//  LoginPresenter.swift
//  TaekwondoPoints
//
//  Created by cassio on 11/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation


// MARK:- LoginPresenter
final class LoginPresenter: LoginPresentable {
    
    // MARK: - Properties
    weak var view: LoginViewProtocol?
    
    // MARK: - Public API
    init(view: LoginViewProtocol? = nil) {
        self.view = view
    }
    
}

// MARK: - Service Handler
extension LoginPresenter: LoginPresenterServiceHandler {
    func presentCredentials(response: Login.LoadCredentials.Response) {
        let viewModel = Login.LoadCredentials.ViewModel(lembrarMeIsOn: response.lembrarNomeusuario,
                                                        nomeusuarioText: response.nomeusuario)
        view?.displayStoredCredentials(viewModel: viewModel)
    }
    
    func authenticationCompleted(response: Login.Autenticacao.Resposta) {
        guard response.error == nil else {
            handleServiceError(response.error)
            return
        }
        
        let viewModel = Login.Autenticacao.ViewModel(isSuccessful: true, errorTitle: nil, errorDescription: nil)
        view?.loginCompleted(viewModel: viewModel)
    }
    
    private func handleServiceError(_ error: LoginError?) {
        switch error {
        case .missingCredentials:
            let viewModel = Login.Autenticacao.ViewModel(isSuccessful: false,
                                                         errorTitle: "Error",
                                                         errorDescription: "Both fields are mandatory.")
            view?.loginCompleted(viewModel: viewModel)
            
        case .loginFailed(let message), .registerFailed(let message):
            let viewModel = Login.Autenticacao.ViewModel(isSuccessful: false,
                                                         errorTitle: "Error",
                                                         errorDescription: String(describing: message))
            view?.loginCompleted(viewModel: viewModel)
            
        default:
            break
        }
    }
}
