//
//  LoginInteractor.swift
//  TaekwondoPoints
//
//  Created by cassio on 11/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic {
    func doSomething(request: Login.Something.Request)
//    func doSomethingElse(request: Login.SomethingElse.Request)
}

protocol LoginDataStore {
    //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore {
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    private let keychain: TaeKondoPontosKeychain
    
    //var name: String = ""

    // MARK: Do something (and send response to LoginPresenter)

    func doSomething(request: Login.Something.Request) {
        worker = LoginWorker()
        worker?.doSomeWork()
        let rememberUsername = userDefaults.rememberUsername ?? true
        let username = keychain.username
        let response = Login.LoadCredentials.Response(lembrarNomeusuario: rememberUsername, nomeusuario: username)
        presenter.presentCredentials(response: response)
 
    func login(request: Login.Autenticacao.Solicitar) {
        guard let username = request.usuarionome, let password = request.senha else {
            let response = Login.Autenticacao.Resposta(error: .missingCredentials)
            //presenter.authenticationCompleted(response: response)
            return
        }
}
